export const decks = [
    {
        slug: 'deep',
        has_landing_page: true,
        title: 'Deep',
        sku: 'ttk-c-deep-1',
        rating: 4.9,
        rating_count: 275,
        imageSrc: '/images/cards/deep1-4x5.webp',
		imageAlt: "Card variant Deep",
        tags: ['date', 'relationship', 'deep talk'],
        is_topseller: true,
        occasion: ['deep talk', 'date', 'couple', 'relationship'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/24179886317',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1729878628988847821',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMEawK/',
            lazada: 'https://www.lazada.co.id/products/i8231290361.html',
        }
    },
    {
        slug: 'hangout',
        has_landing_page: true,
        title: 'Hangout',
        sku: 'ttk-c-hangout-1',
        rating: 4.8,
        rating_count: 131,
        imageSrc: '/images/cards/hangout1-4x5.webp',
		imageAlt: "Card variant Hangout",
        tags: ['fun', 'challenge'],
        is_topseller: true,
        occasion: ['nongkrong', 'date'],
        link_online_shop: {
            shopee: "https://shopee.co.id/product/73180818/24229872610/",
            tiktokshop: "https://shop-id.tokopedia.com/view/product/1729878736879519437",
            tokopedia: "https://tk.tokopedia.com/ZSHcxxR8m/",
            lazada: "https://www.lazada.co.id/products/i8231302294.html",
        }
    },
    {
        slug: 'tot',
        has_landing_page: true,
        title: 'This or That',
        sku: 'ttk-c-tot-1',
        rating: 4.9,
        rating_count: 275,
        imageSrc: '/images/cards/tot1-4x5.webp',
		imageAlt: "Card variant This or That",
        tags: ['fun', 'first date'],
        is_topseller: false,
        occasion: ['nongkrong', 'first date', 'ice breaking'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/26852148737',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1729878837309310669',
            tokopedia: 'https://tk.tokopedia.com/ZSHKM4r6B/',
            lazada: 'https://www.lazada.co.id/products/i8231226882.html',
        }
    },
    {
        slug: 'family99',
        has_landing_page: true,
        title: 'Family 99',
        sku: 'ttk-c-family99-1',
        rating: 4.9,
        rating_count: 50,
        imageSrc: '/images/cards/family991-4x5.webp',
		imageAlt: "Card variant Family 99",
        tags: ['fun', 'challenge', 'games'],
        is_topseller: true,
        occasion: ['nongkrong', 'ice breaking', 'gathering party'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/28400024327',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1729879096179525325',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMojtr/',
            lazada: 'https://www.lazada.co.id/products/i8231226945.html',
        }
    },
    {
        slug: 'berani-gak',
        has_landing_page: true,
        title: 'Berani Gak?',
        sku: 'ttk-c-bg-1',
        rating: 4.9,
        rating_count: 117,
        imageSrc: '/images/cards/bg1-4x5.webp',
		imageAlt: "Card variant Berani Gak?",
        tags: ['fun', 'challenge'],
        is_topseller: false,
        occasion: ['nongkrong'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/25186996457',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1730281694476732109',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMV1nd/',
            lazada: 'https://www.lazada.co.id/products/i8271416052.html',
        }
    },
    {
        slug: 'badboy',
        has_landing_page: true,
        title: 'Badboy',
        sku: 'ttk-c-badboy-1',
        rating: 5,
        rating_count: 9,
        imageSrc: '/images/cards/badboy1-4x5.webp',
		imageAlt: "Card variant Bad Boy",
        tags: ['fun', 'challenge'],
        is_topseller: false,
        occasion: ['nongkrong', 'night talk'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/40053646045',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1731618372315809485',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMQNWP/',
            lazada: 'https://www.lazada.co.id/products/i8738920035.html',
        }
    },
    {
        slug: 'tot-2',
        has_landing_page: true,
        title: 'This or That 2',
        sku: 'ttk-c-tot-2',
        rating: 4.9,
        rating_count: 25,
        imageSrc: '/images/cards/tot21-4x5.webp',
		imageAlt: "Card variant This or That 2",
        tags: ['fun', 'first date'],
        is_topseller: true,
        occasion: ['nongkrong', 'first date', 'ice breaking', 'gathering party'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/43372292025/',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1732749024385205965',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMDHxw/',
            lazada: 'https://www.lazada.co.id/products/i8738900654.html',
        }
    },
    {
        slug: 'love_sparks',
        has_landing_page: true,
        title: 'Love Sparks',
        sku: 'ttk-c-lovesparks-1',
        rating: 4.9,
        rating_count: 15,
        imageSrc: '/images/cards/love_sparks_main.webp',
		imageAlt: "Card variant Love Sparks",
        tags: ['couple', 'date', 'relationship'],
        is_topseller: false,
        // occasion: ['fun', 'first date'],
        link_online_shop: {
            shopee: 'https://shopee.co.id/product/73180818/49155055453/',
            tiktokshop: 'https://shop-id.tokopedia.com/view/product/1734262828001953485',
            tokopedia: 'https://tk.tokopedia.com/ZSHKMKNSY/',
            // lazada: 'https://www.lazada.co.id/products/i8738900654.html',
        }
    },
]

export const decksTopSellers = decks.filter(deck => deck.is_topseller)